export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const ADD_MOVIE_TO_FAVORITES = "ADD_MOVIE_TO_FAVORITES"
export const DELETE_FAVORITE_MOVIE = "DELETE_FAVORITE_MOVIE"
export const SAVE_SEARCH = "SAVE_SEARCH"